# Generated by Django 2.1.1 on 2018-09-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180902_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstance',
            old_name='book',
            new_name='product',
        ),
    ]
